`define INPUT_FILE "/Users/dattarij/Documents/Penn_Folder/Classwork/Spring_2022/CIS_471/cis471-labs/lab4-pipeline/test_data/test_br.ctrace"
`define OUTPUT_FILE "/Users/dattarij/Documents/Penn_Folder/Classwork/Spring_2022/CIS_471/cis471-labs/lab4-pipeline/test_data/test_br.output"
`define ORIG_INPUT_FILE "/Users/dattarij/Documents/Penn_Folder/Classwork/Spring_2022/CIS_471/cis471-labs/lab4-pipeline/test_data/test_br.trace"
`define MEMORY_IMAGE_FILE "/Users/dattarij/Documents/Penn_Folder/Classwork/Spring_2022/CIS_471/cis471-labs/lab4-pipeline/test_data/test_br.hex"
`define TEST_CASE "test_br"
`define VCD_FILE "test_br.vcd"
