`define INPUT_FILE "/Users/dattarij/Documents/cis471-labs/lab5-superscalar/test_data/test_all.ctrace"
`define OUTPUT_FILE "/Users/dattarij/Documents/cis471-labs/lab5-superscalar/test_data/test_all.output"
`define ORIG_INPUT_FILE "/Users/dattarij/Documents/cis471-labs/lab5-superscalar/test_data/test_all.trace"
`define MEMORY_IMAGE_FILE "/Users/dattarij/Documents/cis471-labs/lab5-superscalar/test_data/test_all.hex"
`define TEST_CASE "test_all"
`define VCD_FILE "test_all.vcd"
